[package]
name = "ezk-stun"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["net", "macros", "rt"] }
bytes = "1"
bytesstr = "1"

stun-types = { path = "../stun-types", package = "ezk-stun-types" }