[workspace]

members = [
    "crates/sdp-types",
    "crates/sip-core",
    "crates/sip-types",
    "crates/sip-ua",
    "crates/stun",
    "examples",

    # Placeholder for the ezk-crate
    "crates/placeholder",
]
